In [ ]:
import pandas as pd
import numpy as np
heart = pd.read_csv('/content/heart.csv')
heart

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [ ]:
heart.describe()

age         sex          cp  ...          ca        thal      target
count  303.000000  303.000000  303.000000  ...  303.000000  303.000000  303.000000
mean    54.366337    0.683168    0.966997  ...    0.729373    2.313531    0.544554
std      9.082101    0.466011    1.032052  ...    1.022606    0.612277    0.498835
min     29.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%     47.500000    0.000000    0.000000  ...    0.000000    2.000000    0.000000
50%     55.000000    1.000000    1.000000  ...    0.000000    2.000000    1.000000
75%     61.000000    1.000000    2.000000  ...    1.000000    3.000000    1.000000
max     77.000000    1.000000    3.000000  ...    4.000000    3.000000    1.000000

[8 rows x 14 columns]

In [ ]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
X = heart.drop('target', axis = 'columns')
y = heart.target
len(X), len(y)

(303, 303)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
len(X_train), len(X_test), len(y_train), len(y_test)

(242, 61, 242, 61)

In [ ]:
#USING DECISION TREE CLASSIFIER

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
predict_y = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score,confusion_matrix
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import roc_auc_score

print("Decision Tree Classifier Model Score is:", accuracy_score(y_test, predict_y))
print("Confusion Matrix is:\n", confusion_matrix(y_test, predict_y))
print("Precision Score is:", precision_score(y_test, predict_y))

Decision Tree Classifier Model Score is: 0.7049180327868853
Confusion Matrix is:
 [[22  9]
 [ 9 21]]
Precision Score is: 0.7


In [ ]:
#USING NAIVE_BAYES CLASSIFIER MODEL

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)
predict_N = model.predict(X_test)

print("Naïve Bayes Classifier Model Score is:", accuracy_score(y_test, predict_N))
print("Confusion Matrix is:\n", confusion_matrix(y_test, predict_N))
print("Precision Score is:", precision_score(y_test, predict_N))

Naïve Bayes Classifier Model Score is: 0.8524590163934426
Confusion Matrix is:
 [[25  6]
 [ 3 27]]
Precision Score is: 0.8181818181818182


In [ ]:
#USING RANDOM FOREST CLASSIFIER

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)
predict_R = model.predict(X_test)

print("Random Forest Classifier Model Score is:", accuracy_score(y_test, predict_R))
print("Confusion Matrix is:\n", confusion_matrix(y_test, predict_R))
print("Precision Score is:", precision_score(y_test, predict_R))

Random Forest Classifier Model Score is: 0.8360655737704918
Confusion Matrix is:
 [[24  7]
 [ 3 27]]
Precision Score is: 0.7941176470588235


In [ ]:
#MODEL ACCURACY OF ALL CLASSIFIER MODELS

In [ ]:
print("Decision Tree Classifier Model Score is:", accuracy_score(y_test, predict_y))
print("Random Forest Classifier Model Score is:", accuracy_score(y_test, predict_R))
print("Naïve Bayes Classifier Model Score is:", accuracy_score(y_test, predict_N))

Decision Tree Classifier Model Score is: 0.7049180327868853
Random Forest Classifier Model Score is: 0.8360655737704918
Naïve Bayes Classifier Model Score is: 0.8524590163934426
